name: Format Java

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download google-java-format
        run: |
          curl -L -o gjf.jar https://github.com/google/google-java-format/releases/download/v1.17.0/google-java-format-1.17.0-all-deps.jar
      - name: Format code
        run: |
          find . -name "*.java" > files.txt
          xargs -a files.txt java -jar gjf.jar --replace
      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-format Java code"
          git push
