name: CI Workflow

on: [push]

jobs:
  linux-build:
    runs-on: ubuntu-latest
    name: Build and Test on Linux

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build project
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

      - name: Save test results
        uses: actions/upload-artifact@v4
        with:
          name: test-results-linux
          path: build/test-results/test

  windows-build:
    runs-on: self-hosted
    name: Build and Analyze on Windows

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Build project
        run: gradlew.bat build

      - name: Run static analysis
        run: gradlew.bat check

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-windows
          path: build/libs
